default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      groups: "amantac-founders-group",
      release_notes: <<-NOTES
      🎉🎉🎉 AMANTAC "V1" is now available for testing! 🎉🎉🎉

      🚀 The latest version includes exciting new features that we would like you to test before we move to production. Your feedback is crucial to ensure everything runs smoothly. 🚀

      📝 Please review the new features and let us know if you encounter any issues or have suggestions for improvements.

      Best regards,
      Omar Ameer 😊
      NOTES
    )
  end
end
