# MINE: Android Fastlane with Firebase App Distribution Workflow ------------------------------------------------------------------------------------------------------------

name: Android Fastlane with Firebase App Distribution Workflow

on:
  # push:
  #   branches:
  #     - mobile-app-stable

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # If there was an error, then run this: "cd android" then "bundle lock --add-platform x86_64-linux"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4"
          bundler-cache: true
          working-directory: android

      - name: Build and Distribute App
        env:
          APP_ID: ${{ secrets.APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_OPTIONS_ANDROID_API_KEY: ${{ secrets.FIREBASE_OPTIONS_ANDROID_API_KEY }}
          FIREBASE_OPTIONS_ANDROID_APP_ID: ${{ secrets.FIREBASE_OPTIONS_ANDROID_APP_ID }}
          FIREBASE_OPTIONS_IOS_API_KEY: ${{ secrets.FIREBASE_OPTIONS_IOS_API_KEY }}
          FIREBASE_OPTIONS_IOS_APP_ID: ${{ secrets.FIREBASE_OPTIONS_IOS_APP_ID }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android

      # - name: Send Email on Success
      #   if: success()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.gmail.com
      #     server_port: 465
      #     username: ${{ secrets.SMTP_USERNAME }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Build and Distribution Successful
      #     body: |
      #       Dear AMANTAC Founders,
      #       🎉🎉🎉 AMANTAC "V1" is now available for testing! 🎉🎉🎉
      #       🚀 The latest version includes exciting new features that we would like you to test before we move to production. Your feedback is crucial to ensure everything runs smoothly. 🚀

      #       Please review the new features and let us know if you encounter any issues or have suggestions for improvements.
      #       Best regards,
      #       Omar Ameer 😊
      #     to: omar.ameer2333@gmail.com, omar82199@gmail.com, nooranhossam209@gmail.com
      #     from: ${{ secrets.SMTP_USERNAME }}
# Mohamed Ali's: Android Fastlane with Firebase App Distribution Workflow ------------------------------------------------------------------------------------------------------------

# name: Android Fastlane with Firebase App Distribution Workflow

# on:
#   push:
#     branches:
#       - mobile-app-stable

# jobs:
#   distribution_to_firebase:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout My Repository
#         uses: actions/checkout@v2

#       - name: Setup JDK 11
#         uses: actions/setup-java@v2
#         with:
#           distribution: "temurin"
#           java-version: "11"

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: "3.3.4"
#           bundler-cache: false # Disable bundler-cache to manage dependencies manually

#       - name: Update Gemfile.lock platforms
#         run: |
#           cd android
#           bundle lock --add-platform x86_64-linux
#           bundle lock --add-platform ruby

#       - name: Install Ruby Dependencies
#         run: |
#           cd android
#           bundle install

#       - name: Flutter Build Android App And Upload To Firebase
#         env:
#           APP_ID: ${{ secrets.APP_ID }}
#           FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
#           FIREBASE_OPTIONS_ANDROID_API_KEY: ${{ secrets.FIREBASE_OPTIONS_ANDROID_API_KEY }}
#           FIREBASE_OPTIONS_ANDROID_APP_ID: ${{ secrets.FIREBASE_OPTIONS_ANDROID_APP_ID }}
#           FIREBASE_OPTIONS_IOS_API_KEY: ${{ secrets.FIREBASE_OPTIONS_IOS_API_KEY }}
#           FIREBASE_OPTIONS_IOS_APP_ID: ${{ secrets.FIREBASE_OPTIONS_IOS_APP_ID }}
#         run: |
#           cd android
#           bundle exec fastlane android firebase_distribution

